const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);
const matches={
  'dizel-sputnik':{title:'Дизель — Спутник',date:'14 сентября 2026',time:'19:00',place:'Ледовая арена, Вологда',prices:{A:550,B:400,C:300},ics:'20260914T190000'},
  'dizel-sever':{title:'Дизель — Север',date:'5 октября 2026',time:'17:00',place:'Ледовая арена, Вологда',prices:{A:600,B:450,C:320},ics:'20261005T170000'},
  'dizel-vympel':{title:'Дизель — Вымпел',date:'19 октября 2026',time:'18:00',place:'Ледовая арена, Вологда',prices:{A:520,B:390,C:280},ics:'20261019T180000'},
  'olimp-dizel':{title:'Олимп — Дизель',date:'21 сентября 2026',time:'18:30',place:'Выездной матч',prices:{A:0,B:0,C:0},ics:'20260921T183000'}
};
const protocols={
  'final-north':{title:'Дизель — Север',date:'27 апреля 2026',score:'4:1',text:'Финальный матч завершился уверенной победой «Дизеля». Команда контролировала темп, реализовала большинство и сохранила преимущество до финальной сирены.'},
  'semi-olimp':{title:'Дизель — Олимп',date:'20 апреля 2026',score:'3:2 ОТ',text:'Победная шайба была заброшена в овертайме после быстрой контратаки.'},
  'vympel-dizel':{title:'Вымпел — Дизель',date:'12 апреля 2026',score:'2:5',text:'Голевая серия первой тройки нападения помогла команде забрать важные очки.'}
};
const players={
  kovalev:{name:'Андрей Ковалёв',num:'31',role:'Вратарь',stats:'92% отражённых бросков',text:'Надёжно играет на последнем рубеже и быстро начинает атаки первым пасом.'},
  morozov:{name:'Илья Морозов',num:'74',role:'Защитник',stats:'18 силовых приёмов',text:'Жёсткий защитник с хорошим первым пасом и стабильной игрой в меньшинстве.'},
  egorov:{name:'Павел Егоров',num:'11',role:'Нападающий',stats:'14 очков',text:'Скоростной нападающий, полезный в большинстве и быстрых сменах.'},
  sidorov:{name:'Никита Сидоров',num:'88',role:'Нападающий',stats:'9 шайб',text:'Один из лидеров атаки, хорошо открывается на пятаке и бросает в касание.'},
  belov:{name:'Максим Белов',num:'5',role:'Защитник',stats:'23 блокированных броска',text:'Отвечает за порядок в обороне и силовую борьбу у борта.'},
  orlov:{name:'Дмитрий Орлов',num:'1',role:'Вратарь',stats:'2 сухих матча',text:'Хладнокровно играет под давлением и уверенно действует на добиваниях.'}
};
const articles={
  champions:{title:'«Дизель» стал семикратным чемпионом Вологды',date:'27 апреля 2026',body:'Команда завершила финальную серию победой и вновь подтвердила статус одного из главных хоккейных клубов региона.'},
  tickets:{title:'Открыта продажа билетов на домашний матч',date:'Афиша',body:'Болельщикам доступны секторы A, B и C. Электронный заказ сохраняется в личном кабинете сайта.'},
  partners:{title:'Клуб приглашает партнёров к сотрудничеству',date:'Партнёры',body:'Для бизнеса доступны рекламные пакеты на арене, брендированные активности и совместные проекты с болельщиками.'},
  calendar:{title:'Опубликован календарь первого круга',date:'Матч-центр',body:'Расписание домашних и выездных игр доступно в разделе матчей. Игры можно добавить в личный календарь.'},
  media:{title:'Фото с чемпионского матча',date:'Медиа',body:'В медиаразделе опубликована подборка кадров с трибун, льда и раздевалки после финальной сирены.'}
};
const searchIndex=[
  ['Главная','index.html','Анонсы, титулы, новости и матч-центр'],['Матчи и результаты','matches.html','Календарь, протоколы и таблица'],['Билеты','tickets.html','Покупка билетов и история заказов'],['Команда','team.html','Игроки, тренеры и профили'],['Новости','news.html','Клубная лента и интервью'],['Медиа','media.html','Фото и видео'],['Болельщикам','fans.html','Фан-клуб, правила, атрибутика'],['История','history.html','Семь чемпионств и развитие клуба'],['Контакты','contacts.html','Адрес, телефон, email и форма связи']
];
function toast(text){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=text;t.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
function openDialog(el){if(!el)return;if(typeof el.showModal==='function')el.showModal();else el.setAttribute('open','')}
function closeDialog(el){if(!el)return;if(typeof el.close==='function')el.close();else el.removeAttribute('open')}
$$('[data-modal-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(b.closest('dialog'))));
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)closeDialog(d)}));
const page=document.body.dataset.page;$$('[data-page-link]').forEach(a=>a.classList.toggle('active',a.dataset.pageLink===page));
const nav=$('.site-nav'),menu=$('[data-menu-toggle]');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',open)});nav?.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');document.body.classList.remove('menu-open');menu?.setAttribute('aria-expanded','false')}});
const io='IntersectionObserver' in window?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.14}):null;$$('.reveal').forEach(el=>io?io.observe(el):el.classList.add('visible'));
$$('[data-counter]').forEach(el=>{const end=Number(el.dataset.counter),duration=900,start=performance.now();function tick(now){const p=Math.min(1,(now-start)/duration);el.textContent=Math.round(end*p);if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)});
const ticketModal=$('[data-ticket-modal]'),ticketForm=$('[data-ticket-form]'),matchSelect=$('[data-ticket-match]'),sectorPicker=$('[data-sector-picker]'),qtyInput=$('[data-ticket-qty]'),summary=$('[data-ticket-summary]'),ticketStatus=$('[data-ticket-status]');
function fillMatches(selected){if(!matchSelect)return;matchSelect.innerHTML=Object.entries(matches).filter(([,m])=>m.prices.A>0).map(([id,m])=>`<option value="${id}">${m.title} · ${m.date} · ${m.time}</option>`).join('');if(selected&&matches[selected]?.prices.A>0)matchSelect.value=selected;renderSectors()}
function renderSectors(){if(!matchSelect||!sectorPicker)return;const m=matches[matchSelect.value];sectorPicker.innerHTML=Object.entries(m.prices).map(([s,p],i)=>`<label><input type="radio" name="sector" value="${s}" ${i===0?'checked':''} required><span>Сектор ${s}<br>${money(p)}</span></label>`).join('');$$('input',sectorPicker).forEach(i=>i.addEventListener('change',updateTicketSummary));updateTicketSummary()}
function updateTicketSummary(){if(!matchSelect||!summary)return;const m=matches[matchSelect.value],sector=$('input[name="sector"]:checked',sectorPicker)?.value||'A',qty=Math.max(1,Number(qtyInput?.value||1)),total=m.prices[sector]*qty;summary.textContent=`${m.title}, сектор ${sector}, ${qty} шт. Итого: ${money(total)}`}
function openTicket(matchId){fillMatches(matchId);if(ticketStatus)ticketStatus.textContent='';openDialog(ticketModal)}
$$('[data-buy-ticket]').forEach(btn=>btn.addEventListener('click',()=>openTicket(btn.dataset.match||'dizel-sputnik')));
matchSelect?.addEventListener('change',renderSectors);qtyInput?.addEventListener('input',updateTicketSummary);
ticketForm?.addEventListener('submit',e=>{e.preventDefault();if(!ticketForm.checkValidity()){ticketForm.reportValidity();return}const data=new FormData(ticketForm),m=matches[data.get('match')],sector=data.get('sector'),qty=Number(data.get('qty')),total=m.prices[sector]*qty,id='DZ-'+Date.now().toString().slice(-6);const order={id,type:'Билеты',title:m.title,date:m.date,time:m.time,sector,qty,total,name:data.get('name'),phone:data.get('phone'),email:data.get('email'),created:new Date().toLocaleString('ru-RU')};const orders=store.get('dizelOrders',[]);orders.unshift(order);store.set('dizelOrders',orders);ticketStatus.innerHTML=`Заказ <b>${id}</b> оформлен. Электронный билет отправлен на ${order.email}.`;toast('Билетный заказ оформлен');renderOrders();renderOrdersMini();ticketForm.reset();fillMatches()});
$$('[data-calendar]').forEach(btn=>btn.addEventListener('click',()=>{const m=matches[btn.dataset.match];if(!m)return;const ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nSUMMARY:${m.title}\nDTSTART:${m.ics}\nLOCATION:${m.place}\nDESCRIPTION:Матч ХК Дизель\nEND:VEVENT\nEND:VCALENDAR`;const blob=new Blob([ics],{type:'text/calendar'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${m.title.replace(/\s+/g,'_')}.ics`;a.click();URL.revokeObjectURL(url);toast('Файл календаря создан')}));
function showInfo(html){const modal=$('[data-info-modal]'),content=$('[data-info-content]');if(content)content.innerHTML=html;openDialog(modal)}
$$('[data-protocol]').forEach(btn=>btn.addEventListener('click',()=>{const p=protocols[btn.dataset.protocol]||protocols['final-north'];showInfo(`<p class="eyebrow">Протокол</p><h2>${p.title}</h2><p class="lead">${p.date} · счёт ${p.score}</p><p>${p.text}</p>`)}));
$$('[data-tabs]').forEach(tabs=>$$('button',tabs).forEach(btn=>btn.addEventListener('click',()=>{$$('button',tabs).forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===btn.dataset.tab))})));
$$('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;$$('[data-role]').forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.role!==f))}));
$$('[data-player]').forEach(btn=>btn.addEventListener('click',()=>{const p=players[btn.dataset.player];showInfo(`<p class="eyebrow">Профиль игрока</p><div class="grid two"><div class="player-photo">${p.num}</div><div><h2>${p.name}</h2><p class="lead">${p.role}</p><p><b>${p.stats}</b></p><p>${p.text}</p></div></div>`)}));
$$('[data-article]').forEach(btn=>btn.addEventListener('click',()=>{const a=articles[btn.dataset.article];showInfo(`<p class="eyebrow">${a.date}</p><h2>${a.title}</h2><p class="lead">${a.body}</p><div class="button-row"><button class="btn btn-outline" data-share type="button">Поделиться</button></div>`);$('[data-share]')?.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:a.title,text:a.body,url:location.href});else{await navigator.clipboard.writeText(location.href);toast('Ссылка скопирована')}}catch{}})}));
let newsFilter='all';function applyNews(){const q=($('[data-news-search]')?.value||'').toLowerCase().trim();let count=0;$$('[data-news]').forEach(card=>{const okCat=newsFilter==='all'||card.dataset.news.includes(newsFilter),okText=card.textContent.toLowerCase().includes(q),show=okCat&&okText;card.style.display=show?'':'none';if(show)count++});const empty=$('[data-news-empty]');if(empty)empty.style.display=count?'none':'block'}$$('[data-news-filter]').forEach(btn=>btn.addEventListener('click',()=>{$$('[data-news-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');newsFilter=btn.dataset.newsFilter;applyNews()}));$('[data-news-search]')?.addEventListener('input',applyNews);
$$('[data-gallery]').forEach(btn=>btn.addEventListener('click',()=>showInfo(`<p class="eyebrow">Фотогалерея</p><h2>${btn.dataset.gallery==='fans'?'Трибуны и болельщики':'Игровые моменты'}</h2><div class="gallery-grid"><span></span><span></span><span></span><span></span><span></span><span></span></div><p>Альбом открыт внутри сайта.</p>`)));
$$('[data-video]').forEach(btn=>btn.addEventListener('click',()=>showInfo(`<p class="eyebrow">Видео</p><h2>${btn.dataset.video==='interview'?'Интервью капитана':'Лучшие моменты матча'}</h2><div class="video-box"><span>▶</span></div><p>Видеозапись открыта во встроенном плеере клуба.</p>`)));
$$('[data-simple-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const status=$('.form-status',form);if(status)status.textContent=form.dataset.success||'Заявка отправлена. Мы свяжемся с вами.';toast('Форма отправлена');form.reset()}));
const searchModal=$('[data-search-modal]'),searchInput=$('[data-search-input]'),searchResults=$('[data-search-results]');function renderSearch(q=''){if(!searchResults)return;const query=q.toLowerCase().trim();const rows=searchIndex.filter(([t,,d])=>!query||(t+' '+d).toLowerCase().includes(query));searchResults.innerHTML=rows.length?rows.map(([t,u,d])=>`<a href="${u}"><b>${t}</b><span>${d}</span></a>`).join(''):'<p>Ничего не найдено.</p>'}$('[data-search-open]')?.addEventListener('click',()=>{renderSearch();openDialog(searchModal);setTimeout(()=>searchInput?.focus(),70)});searchInput?.addEventListener('input',e=>renderSearch(e.target.value));
let cart=store.get('dizelCart',[]);function cartCount(){return cart.reduce((s,i)=>s+i.qty,0)}function updateCartCount(){$$('[data-cart-count]').forEach(el=>el.textContent=cartCount())}function renderCart(){const box=$('[data-cart-items]');if(!box)return;if(!cart.length){box.innerHTML='<p>Корзина пуста. Добавьте атрибутику в разделе «Болельщикам».</p>';updateCartCount();return}const total=cart.reduce((s,i)=>s+i.qty*i.price,0);box.innerHTML=cart.map((i,idx)=>`<div class="drawer-item"><div><b>${i.product}</b><p>${i.qty} × ${money(i.price)}</p></div><button type="button" data-remove-cart="${idx}">Удалить</button></div>`).join('')+`<div class="order-summary">Итого: ${money(total)}</div>`;$$('[data-remove-cart]').forEach(b=>b.addEventListener('click',()=>{cart.splice(Number(b.dataset.removeCart),1);store.set('dizelCart',cart);renderCart();updateCartCount()}));updateCartCount()}function openDrawer(d){d?.classList.add('open');d?.setAttribute('aria-hidden','false');document.body.classList.add('drawer-open')}function closeDrawers(){$$('.drawer.open').forEach(d=>{d.classList.remove('open');d.setAttribute('aria-hidden','true')});document.body.classList.remove('drawer-open')}$$('[data-cart-open]').forEach(b=>b.addEventListener('click',()=>{renderCart();openDrawer($('[data-cart-drawer]'))}));$$('[data-orders-open]').forEach(b=>b.addEventListener('click',()=>{renderOrders();openDrawer($('[data-orders-drawer]'))}));$$('[data-drawer-close]').forEach(b=>b.addEventListener('click',closeDrawers));$$('[data-add-cart]').forEach(btn=>btn.addEventListener('click',()=>{const product=btn.dataset.product,price=Number(btn.dataset.price),item=cart.find(i=>i.product===product);if(item)item.qty++;else cart.push({product,price,qty:1});store.set('dizelCart',cart);renderCart();toast('Товар добавлен в корзину')}));
$('[data-shop-order-form]')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!cart.length){toast('Корзина пуста');return}if(!form.checkValidity()){form.reportValidity();return}const total=cart.reduce((s,i)=>s+i.qty*i.price,0),id='SHOP-'+Date.now().toString().slice(-6);const orders=store.get('dizelOrders',[]);orders.unshift({id,type:'Магазин',title:'Клубная атрибутика',items:cart,total,name:form.querySelector('[name="name"]')?.value||'',phone:form.querySelector('[name="phone"]')?.value||'',created:new Date().toLocaleString('ru-RU')});store.set('dizelOrders',orders);cart=[];store.set('dizelCart',cart);renderCart();renderOrders();form.reset();$('[data-shop-status]').innerHTML=`Заказ <b>${id}</b> оформлен. Менеджер свяжется с вами.`;toast('Заказ оформлен')});
function renderOrders(){const box=$('[data-orders-list]');if(!box)return;const orders=store.get('dizelOrders',[]);box.innerHTML=orders.length?orders.map(o=>`<div class="order-mini"><div><b>${o.type}: ${o.title}</b><p>${o.date?`${o.date} · ${o.time||''}<br>`:''}${o.sector?`Сектор ${o.sector}, ${o.qty} шт.<br>`:''}Сумма: ${money(o.total)}<br>${o.created}</p></div></div>`).join(''):'<p>Заказов пока нет. После покупки билета или атрибутики история появится здесь.</p>'}
function renderOrdersMini(){const box=$('[data-orders-mini]');if(!box)return;const orders=store.get('dizelOrders',[]).slice(0,3);box.innerHTML=orders.length?orders.map(o=>`<div class="order-mini"><div><b>${o.type}</b><p>${o.title}<br>${money(o.total)}</p></div></div>`).join(''):'<p>Ваши последние заказы появятся здесь.</p>'}
$('[data-notify]')?.addEventListener('click',async()=>{try{if(!('Notification' in window)){toast('Браузер не поддерживает уведомления');return}const r=await Notification.requestPermission();toast(r==='granted'?'Уведомления включены':'Уведомления не включены')}catch{toast('Не удалось включить уведомления')}});
$('[data-print]')?.addEventListener('click',()=>window.print());
fillMatches();renderCart();renderOrdersMini();
